// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMods(arg1) {
  return window['go']['backend']['App']['GetMods'](arg1);
}

export function GetUserHomeDir() {
  return window['go']['backend']['App']['GetUserHomeDir']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['backend']['App']['MoveFile'](arg1, arg2);
}

export function MoveFiles(arg1, arg2) {
  return window['go']['backend']['App']['MoveFiles'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['backend']['App']['OpenFileDialog']();
}
