// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DeleteFile(arg1:string):Promise<backend.DeleteFileResult>;

export function GetMods(arg1:string):Promise<Array<string>>;

export function GetUserHomeDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MoveFile(arg1:string,arg2:string):Promise<backend.MoveFileResult>;

export function OpenFileDialog():Promise<backend.OpenFileDialogResult>;
