// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMods(arg1:string):Promise<Array<string>>;

export function GetUserHomeDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MoveFile(arg1:string,arg2:string):Promise<string>;

export function MoveFiles(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function OpenFileDialog():Promise<Array<string>>;
